### ISSUE TITLE
Images are not stored as data-urls

### ISSUE THREAD

**Issue by jtheisen** [html-screen-capture-js/html-screen-capture-js#6] opened 2019-06-21 14:41 UTC
The documentation claims that images are transformed to data-urls, but that doesn't happen in a small test case I made:

https://cfxwh.codesandbox.io/

I also tried giving an explicit `imageFormatForDataUrl` option, but that doesn't make a difference.

What do I miss here?

**Comment by urikalish** [comment] 2019-08-28 17:50
I encountered no such problem. Can you please run the demo on the latest release and tell me if you see a problem?
https://github.com/html-screen-capture-js/html-screen-capture-js#try-the-demo

**Comment by urikalish** [comment] 2019-09-01 08:18
Unable to reproduce. Closing. Please reopen an issue if needed.

**Closed** 2019-09-01 08:17 UTC
